# Generated by Django 6.0.1 on 2026-02-09 10:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_resultat_utilisateur'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lecon',
            name='contenu',
        ),
        migrations.RemoveField(
            model_name='utilisateur',
            name='email',
        ),
        migrations.RemoveField(
            model_name='utilisateur',
            name='nom',
        ),
        migrations.RemoveField(
            model_name='utilisateur',
            name='prenom',
        ),
        migrations.RemoveField(
            model_name='utilisateur',
            name='role',
        ),
        migrations.AddField(
            model_name='lecon',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='utilisateur',
            name='niveau',
            field=models.CharField(default='Débutant', max_length=50),
        ),
        migrations.AddField(
            model_name='utilisateur',
            name='user',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='profil', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='exercice',
            name='reponse',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='resultat',
            name='utilisateur',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resultats', to='core.utilisateur'),
        ),
    ]
