# Generated by Django 6.0.1 on 2026-02-09 16:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_remove_lecon_contenu_remove_utilisateur_email_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lecon',
            name='description',
        ),
        migrations.AddField(
            model_name='resultat',
            name='feedback_ia',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='resultat',
            name='reponse_donnee',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='exercice',
            name='reponse',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='lecon',
            name='titre',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='resultat',
            name='utilisateur',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.utilisateur'),
        ),
        migrations.AlterField(
            model_name='utilisateur',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
