# Generated by Django 6.0.2 on 2026-02-16 15:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_set_date_defaults_and_alter_fields'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='exercice',
            options={'ordering': ['ordre', 'id']},
        ),
        migrations.AlterModelOptions(
            name='lecon',
            options={'ordering': ['ordre', 'titre'], 'verbose_name_plural': 'Leçons'},
        ),
        migrations.AlterModelOptions(
            name='resultat',
            options={'ordering': ['-date'], 'verbose_name_plural': 'Résultats'},
        ),
        migrations.AlterField(
            model_name='exercice',
            name='reponse_correcte',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='lecon',
            name='titre',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='resultat',
            name='exercice',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resultats', to='core.exercice'),
        ),
        migrations.AlterField(
            model_name='resultat',
            name='feedback_ia',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='resultat',
            name='reponse_donnee',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='resultat',
            name='utilisateur',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resultats', to='core.utilisateur'),
        ),
    ]
