# Generated by Django 5.2.11 on 2026-02-17 23:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_niveaux_et_progression'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lecon',
            name='niveau_global',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='matiere',
            name='nom',
            field=models.CharField(choices=[('mathematiques', 'Mathématiques'), ('francais', 'Français'), ('histoire_geo', 'Histoire-Géographie'), ('sciences', 'Sciences'), ('anglais', 'Anglais'), ('sciences_vie', 'Sciences de la Vie et de la Terre'), ('physique', 'Physique'), ('chimie', 'Chimie'), ('physique_chimie', 'Physique-Chimie'), ('technologie', 'Technologie'), ('eps', 'EPS'), ('arts', 'Arts Plastiques'), ('musique', 'Musique'), ('ses', 'Sciences Économiques et Sociales'), ('philosophie', 'Philosophie'), ('espagnol', 'Espagnol'), ('allemand', 'Allemand')], max_length=100, unique=True),
        ),
    ]
